version: '3'
services:
  auth:
    build: './auth'
    ports:
      - "3001:3001"
    depends_on: 
      - user

  company:
    build: './company'
    ports:
      - "3004:3004"
    depends_on: 
      - mongodb

  vacancy:
    build: './vacancy'
    ports:
      - "4000:4000"
    depends_on: 
      - mongodb

  user:
    build: './user'
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb

  graphql:
    build: './graphql'
    ports:
      - "3040:3040"
    depends_on: 
      - user
      - company
      - vacancy
      - auth
    # environment:
    #   - MONGO_URI=mongodb://mongodb/nest-microservice
    #   - PAYMENT_ENDPOINT=http://payments:4000/payments
  
  mongodb:
    image: mongo
    ports:
      - "27000:27017"

  mongodb_seed:
    build: './mongo-seed'
    links:
      - mongodb